Repository auth0/jwks-rsa-java, pull requests merged in 2019-09, with the labels that each got.

#68 Improve ObjectMapper use
  src/main/java/com/auth0/jwk/UrlJwkProvider.java
Labels: CH: Changed

#72 Update jackson-databind to address CVE
  build.gradle
Labels: CH: Security, tiny

#73 Fix CI script commit hash
  .circleci/config.yml
Labels: tiny

#74 Release 0.9.0
  CHANGELOG.md
  README.md
Labels: tiny
