Repository auth0/jwks-rsa-java, pull requests merged in 2020-11, with the labels that each got.

#103 Update dependencies
  build.gradle
Labels: CH: Security, review:small

#104 Release 0.14.1
  CHANGELOG.md
  README.md
Labels: review:tiny

#105 Target Java 8
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  settings.gradle
Labels: CH: Changed, tiny

#107 Fix publishing
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: review:small

#106 Release 0.15.0
  CHANGELOG.md
  README.md
Labels: review:tiny
