Repository auth0/jwks-rsa-java, pull requests merged in 2021-02, with the labels that each got.

#113 Release 0.16.0
  CHANGELOG.md
  README.md
Labels: tiny

#115 Allow setting of custom headers
  src/main/java/com/auth0/jwk/JwkProviderBuilder.java
  src/main/java/com/auth0/jwk/UrlJwkProvider.java
  src/test/java/com/auth0/jwk/JwkProviderBuilderTest.java
  src/test/java/com/auth0/jwk/UrlJwkProviderTest.java
Labels: CH: Added, medium

#116 Fix JavaDoc Errors
  src/main/java/com/auth0/jwk/JwkProviderBuilder.java
  src/main/java/com/auth0/jwk/UrlJwkProvider.java
Labels: review:tiny

#114 Add ability to run apiDiff for incompatible changes
  .circleci/config.yml
  build.gradle
  settings.gradle
Labels: medium, tiny
